# Generated by Django 5.2.15 on 2026-06-23 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('libraries', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.CharField(blank=True, max_length=300)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_user_book_save_recent')],
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='uq_user_book_save')],
            },
        ),
        migrations.CreateModel(
            name='UserLibrarySave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.CharField(blank=True, max_length=300)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='libraries.library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_libraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_user_library_save_recent')],
                'constraints': [models.UniqueConstraint(fields=('user', 'library'), name='uq_user_library_save')],
            },
        ),
        migrations.CreateModel(
            name='UserProgramSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.CharField(blank=True, max_length=300)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_user_program_save_recent')],
                'constraints': [models.UniqueConstraint(fields=('user', 'program'), name='uq_user_program_save')],
            },
        ),
    ]
