# Generated by Django 5.2.15 on 2026-06-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('collecting', '수집 중'), ('pending', '계산 대기'), ('ready', '계산 완료'), ('failed', '계산 실패')], db_index=True, default='collecting', max_length=16)),
                ('signal_count', models.PositiveIntegerField(default=0)),
                ('library_signal_count', models.PositiveIntegerField(default=0)),
                ('book_signal_count', models.PositiveIntegerField(default=0)),
                ('program_signal_count', models.PositiveIntegerField(default=0)),
                ('written_review_signal_count', models.PositiveIntegerField(default=0)),
                ('liked_review_signal_count', models.PositiveIntegerField(default=0)),
                ('algorithm_version', models.CharField(blank=True, max_length=40)),
                ('eligible_since', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('count', models.DecimalField(decimal_places=6, default=0, help_text='최근성 가중 관측 횟수라 소수 값을 허용합니다.', max_digits=12)),
                ('rank', models.PositiveIntegerField(default=0, help_text='0은 아직 순위가 부여되지 않은 상태입니다.')),
                ('source_count_library', models.PositiveIntegerField(default=0)),
                ('source_count_book', models.PositiveIntegerField(default=0)),
                ('source_count_program', models.PositiveIntegerField(default=0)),
                ('source_count_review_written', models.PositiveIntegerField(default=0)),
                ('source_count_review_liked', models.PositiveIntegerField(default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preference_items', to='tags.tag')),
                ('user_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='preferences.userpreference')),
            ],
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['status', 'calculated_at'], name='idx_user_pref_status'),
        ),
        migrations.AddIndex(
            model_name='userpreferenceitem',
            index=models.Index(fields=['user_preference', 'rank'], name='idx_user_pref_item_rank'),
        ),
        migrations.AddIndex(
            model_name='userpreferenceitem',
            index=models.Index(fields=['tag'], name='idx_user_pref_item_tag'),
        ),
        migrations.AddConstraint(
            model_name='userpreferenceitem',
            constraint=models.UniqueConstraint(fields=('user_preference', 'tag'), name='uq_user_pref_item_tag'),
        ),
        migrations.AddConstraint(
            model_name='userpreferenceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('rank__gt', 0)), fields=('user_preference', 'rank'), name='uq_user_pref_item_rank'),
        ),
        migrations.AddConstraint(
            model_name='userpreferenceitem',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='user_pref_item_score_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='userpreferenceitem',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 0)), name='user_pref_item_count_gte_0'),
        ),
    ]
