# Generated by Django 5.2.15 on 2026-06-23 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('libraries', '0001_initial'),
        ('programs', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=200)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('like_count', models.PositiveBigIntegerField(default=0)),
                ('moderation_status', models.CharField(choices=[('pending', '검토 대기'), ('visible', '공개'), ('hidden', '숨김')], db_index=True, default='visible', max_length=16)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='libraries.library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(help_text='후기 선택 가능 경험 태그 여부는 serializer/service에서 검증합니다.', on_delete=django.db.models.deletion.PROTECT, related_name='review_links', to='tags.tag')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='community.userreview')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProgramReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(help_text='program.library_id == review.library_id 검증은 serializer/service에서 수행합니다.', on_delete=django.db.models.deletion.PROTECT, related_name='review_references', to='programs.program')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_references', to='community.userreview')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewBookReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_references', to='books.book')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_references', to='community.userreview')),
            ],
        ),
        migrations.CreateModel(
            name='UserReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.userreview')),
            ],
        ),
        migrations.CreateModel(
            name='UserReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.userreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['moderation_status', '-created_at'], name='idx_review_recent'),
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['moderation_status', '-view_count', '-created_at'], name='idx_review_views'),
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['moderation_status', '-like_count', '-created_at'], name='idx_review_likes'),
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['library', 'moderation_status', '-created_at'], name='idx_review_library_recent'),
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['user', '-created_at'], name='idx_review_user_recent'),
        ),
        migrations.AddConstraint(
            model_name='userreview',
            constraint=models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='review_content_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='userreview',
            constraint=models.CheckConstraint(condition=models.Q(('view_count__gte', 0)), name='review_view_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='userreview',
            constraint=models.CheckConstraint(condition=models.Q(('like_count__gte', 0)), name='review_like_count_gte_0'),
        ),
        migrations.AddIndex(
            model_name='reviewtag',
            index=models.Index(fields=['review', 'created_at'], name='idx_review_tag_created'),
        ),
        migrations.AddConstraint(
            model_name='reviewtag',
            constraint=models.UniqueConstraint(fields=('review', 'tag'), name='uq_review_tag'),
        ),
        migrations.AddIndex(
            model_name='reviewprogramreference',
            index=models.Index(fields=['review', 'display_order'], name='idx_review_program_order'),
        ),
        migrations.AddConstraint(
            model_name='reviewprogramreference',
            constraint=models.UniqueConstraint(fields=('review', 'program'), name='uq_review_program_reference'),
        ),
        migrations.AddIndex(
            model_name='reviewbookreference',
            index=models.Index(fields=['review', 'display_order'], name='idx_review_book_order'),
        ),
        migrations.AddConstraint(
            model_name='reviewbookreference',
            constraint=models.UniqueConstraint(fields=('review', 'book'), name='uq_review_book_reference'),
        ),
        migrations.AddIndex(
            model_name='userreviewimage',
            index=models.Index(fields=['review', 'display_order'], name='idx_review_image_order'),
        ),
        migrations.AddIndex(
            model_name='userreviewlike',
            index=models.Index(fields=['user', '-created_at'], name='idx_review_like_user'),
        ),
        migrations.AddIndex(
            model_name='userreviewlike',
            index=models.Index(fields=['review', '-created_at'], name='idx_review_like_review'),
        ),
        migrations.AddConstraint(
            model_name='userreviewlike',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='uq_user_review_like'),
        ),
    ]
