# Generated by Django 5.2.15 on 2026-06-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReviewComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(max_length=200)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.userreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="userreviewcomment",
            index=models.Index(fields=["review", "created_at"], name="idx_review_comment_review"),
        ),
        migrations.AddIndex(
            model_name="userreviewcomment",
            index=models.Index(fields=["user", "-created_at"], name="idx_review_comment_user"),
        ),
        migrations.AddConstraint(
            model_name="userreviewcomment",
            constraint=models.CheckConstraint(
                condition=models.Q(("content", ""), _negated=True),
                name="review_comment_content_not_empty",
            ),
        ),
    ]
