# Generated by Django 5.2.15 on 2026-06-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecommendationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('subtitle', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='idx_daily_theme_active')],
            },
        ),
        migrations.CreateModel(
            name='DailyLibraryRecommendationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_date', models.DateField()),
                ('region_key', models.CharField(max_length=30)),
                ('sido', models.CharField(max_length=40)),
                ('sigungu', models.CharField(blank=True, default='', help_text='빈 문자열은 시군구 미지정 지역 범위 sentinel입니다.', max_length=40)),
                ('algorithm_version', models.CharField(max_length=40)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_sets', to='recommendations.dailyrecommendationtheme')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_home_theme', models.BooleanField(db_index=True, default=False)),
                ('is_profile_selectable', models.BooleanField(default=False)),
                ('analysis_axis', models.CharField(blank=True, choices=[('study', '공부형'), ('book', '책 탐색형'), ('program', '프로그램형'), ('rest', '휴식형')], default='', help_text='빈 문자열은 나의 나들이 분석축 없음 상태를 뜻합니다.', max_length=20)),
                ('requires_location', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_home_theme', 'is_active', 'display_order'], name='idx_purpose_home_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('analysis_axis', ''), _negated=True), ('is_active', True)), fields=('analysis_axis',), name='uq_active_purpose_analysis_axis')],
            },
        ),
        migrations.CreateModel(
            name='PurposeMetricRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_code', models.CharField(max_length=80)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('is_required', models.BooleanField(default=False)),
                ('normalization_rule', models.JSONField(blank=True, default=dict)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_rules', to='recommendations.purpose')),
            ],
        ),
        migrations.CreateModel(
            name='PurposeTagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_scope', models.CharField(choices=[('any', '전체'), ('direct', '직접'), ('review_rollup', '후기 집계'), ('program_rollup', '프로그램 집계'), ('book_rollup', '도서 집계')], max_length=24)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('is_required', models.BooleanField(default=False)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_rules', to='recommendations.purpose')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purpose_rules', to='tags.tag')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLibraryRecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('score_detail', models.JSONField(blank=True, default=dict)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_recommendation_items', to='libraries.library')),
                ('recommendation_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.dailylibraryrecommendationset')),
            ],
            options={
                'indexes': [models.Index(fields=['recommendation_set', 'rank'], name='idx_daily_item_rank')],
                'constraints': [models.UniqueConstraint(fields=('recommendation_set', 'rank'), name='uq_daily_item_rank'), models.UniqueConstraint(fields=('recommendation_set', 'library'), name='uq_daily_item_library')],
            },
        ),
        migrations.CreateModel(
            name='DailyRecommendationTagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_scope', models.CharField(choices=[('any', '전체'), ('direct', '직접'), ('review_rollup', '후기 집계'), ('program_rollup', '프로그램 집계'), ('book_rollup', '도서 집계')], max_length=24)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('is_required', models.BooleanField(default=False)),
                ('normalization_rule', models.JSONField(blank=True, default=dict)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_theme_rules', to='tags.tag')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_rules', to='recommendations.dailyrecommendationtheme')),
            ],
            options={
                'indexes': [models.Index(fields=['theme', 'is_required'], name='idx_daily_tag_required'), models.Index(fields=['tag', 'source_scope'], name='idx_daily_tag_scope')],
                'constraints': [models.UniqueConstraint(fields=('theme', 'tag', 'source_scope'), name='uq_daily_theme_tag_scope')],
            },
        ),
        migrations.CreateModel(
            name='DailyRecommendationMetricRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_code', models.CharField(max_length=80)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('is_required', models.BooleanField(default=False)),
                ('normalization_rule', models.JSONField(blank=True, default=dict)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_rules', to='recommendations.dailyrecommendationtheme')),
            ],
            options={
                'indexes': [models.Index(fields=['theme', 'is_required'], name='idx_daily_metric_required')],
                'constraints': [models.UniqueConstraint(fields=('theme', 'metric_code'), name='uq_daily_theme_metric')],
            },
        ),
        migrations.AddIndex(
            model_name='dailylibraryrecommendationset',
            index=models.Index(fields=['recommendation_date', 'region_key'], name='idx_daily_set_region_date'),
        ),
        migrations.AddConstraint(
            model_name='dailylibraryrecommendationset',
            constraint=models.UniqueConstraint(fields=('recommendation_date', 'region_key', 'algorithm_version'), name='uq_daily_recommendation_set'),
        ),
        migrations.AddIndex(
            model_name='purposemetricrule',
            index=models.Index(fields=['purpose', 'is_required'], name='idx_purpose_metric_required'),
        ),
        migrations.AddConstraint(
            model_name='purposemetricrule',
            constraint=models.UniqueConstraint(fields=('purpose', 'metric_code'), name='uq_purpose_metric'),
        ),
        migrations.AddIndex(
            model_name='purposetagrule',
            index=models.Index(fields=['purpose', 'is_required'], name='idx_purpose_tag_required'),
        ),
        migrations.AddIndex(
            model_name='purposetagrule',
            index=models.Index(fields=['tag', 'source_scope'], name='idx_purpose_tag_scope'),
        ),
        migrations.AddConstraint(
            model_name='purposetagrule',
            constraint=models.UniqueConstraint(fields=('purpose', 'tag', 'source_scope'), name='uq_purpose_tag_scope'),
        ),
    ]
