# Generated by Django 6.0.6 on 2026-06-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_origin', models.CharField(choices=[('official_external', '공식 외부 이미지'), ('system_default', '시스템 대체 이미지'), ('admin_upload', '관리자 업로드')], max_length=32)),
                ('original_url', models.URLField(blank=True, max_length=500)),
                ('file', models.ImageField(blank=True, null=True, upload_to='media-assets/')),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('source_page_url', models.URLField(blank=True, max_length=500)),
                ('source_asset_id', models.CharField(blank=True, max_length=120)),
                ('license_code', models.CharField(blank=True, max_length=80)),
                ('attribution_text', models.TextField(blank=True)),
                ('commercial_use_allowed', models.BooleanField(blank=True, null=True)),
                ('modification_allowed', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['asset_origin', 'is_active'], name='idx_media_origin_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('original_url', ''), ('file', ''), _negated=True), name='media_asset_url_or_file_required'), models.CheckConstraint(condition=models.Q(models.Q(('asset_origin', 'official_external'), _negated=True), ('is_active', False), models.Q(models.Q(('license_code', ''), _negated=True), models.Q(('attribution_text', ''), _negated=True)), _connector='OR'), name='media_asset_official_attribution_required'), models.UniqueConstraint(condition=models.Q(('original_url', ''), _negated=True), fields=('original_url',), name='uq_media_asset_original_url')],
            },
        ),
        migrations.CreateModel(
            name='DefaultMediaAssetRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_domain', models.CharField(choices=[('library', '도서관'), ('program', '프로그램'), ('review', '후기'), ('profile', '프로필')], max_length=24)),
                ('target_code', models.CharField(max_length=80)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_rules', to='media_assets.mediaasset')),
            ],
            options={
                'indexes': [models.Index(fields=['target_domain', 'target_code', 'is_active', 'priority'], name='idx_default_media_lookup')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('target_domain', 'target_code', 'priority'), name='uq_active_default_media_rule')],
            },
        ),
    ]
