# Generated by Django 5.2.15 on 2026-06-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('media_assets', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_sido', models.CharField(blank=True, max_length=40)),
                ('source_sigungu', models.CharField(blank=True, max_length=40)),
                ('source_library_name', models.CharField(blank=True, max_length=120)),
                ('provider_code', models.CharField(max_length=40)),
                ('external_program_key', models.CharField(help_text='원천 ID가 없으면 도서관, 제목, 기간, 원문 URL을 정규화한 안정 해시를 저장합니다.', max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('category_code', models.CharField(choices=[('lecture_humanities', '인문 강좌'), ('reading_writing', '독서·글쓰기'), ('culture_art', '문화·예술'), ('experience_education', '체험·교육'), ('exhibition', '전시'), ('other', '기타')], max_length=32)),
                ('target_text', models.CharField(blank=True, max_length=255)),
                ('target_codes', models.JSONField(blank=True, default=list)),
                ('application_required', models.BooleanField(blank=True, null=True)),
                ('application_start_date', models.DateField(blank=True, null=True)),
                ('application_end_date', models.DateField(blank=True, null=True)),
                ('application_status', models.CharField(blank=True, choices=[('available', '신청가능'), ('closed', '신청마감'), ('not_required', '신청없음')], default='', help_text='조회 전 날짜 기준으로 재계산 가능한 신청 상태 캐시입니다.', max_length=20)),
                ('operation_start_date', models.DateField(blank=True, null=True)),
                ('operation_end_date', models.DateField(blank=True, null=True)),
                ('operation_status', models.CharField(blank=True, choices=[('upcoming', '예정'), ('ongoing', '진행중'), ('ended', '종료')], default='', help_text='조회 전 날짜 기준으로 재계산 가능한 운영 상태 캐시입니다.', max_length=20)),
                ('source_board', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=128)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='libraries.library')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_main', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_usages', to='media_assets.mediaasset')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_method', models.CharField(choices=[('category_rule', '분류 규칙'), ('target_rule', '대상 규칙'), ('metadata_rule', '메타데이터 규칙'), ('manual', '수동')], max_length=24)),
                ('source_field', models.CharField(blank=True, max_length=80)),
                ('score', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='programs.program')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_links', to='tags.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['library', 'is_visible'], name='idx_program_library_visible'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_visible', 'operation_status', 'operation_start_date'], name='idx_program_status_start'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['category_code', 'is_visible'], name='idx_program_category'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('provider_code', 'external_program_key'), name='uq_program_external_key'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('application_start_date__isnull', True), ('application_end_date__isnull', True), ('application_end_date__gte', models.F('application_start_date')), _connector='OR'), name='program_application_period_order'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('operation_start_date__isnull', True), ('operation_end_date__isnull', True), ('operation_end_date__gte', models.F('operation_start_date')), _connector='OR'), name='program_operation_period_order'),
        ),
        migrations.AddIndex(
            model_name='programimage',
            index=models.Index(fields=['program', 'is_active', 'display_order'], name='idx_program_image_order'),
        ),
        migrations.AddConstraint(
            model_name='programimage',
            constraint=models.UniqueConstraint(fields=('program', 'media_asset'), name='uq_program_media_asset'),
        ),
        migrations.AddConstraint(
            model_name='programimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_main', True)), fields=('program',), name='uq_program_active_main_image'),
        ),
        migrations.AddIndex(
            model_name='programtag',
            index=models.Index(fields=['program', 'is_active'], name='idx_program_tag_active'),
        ),
        migrations.AddIndex(
            model_name='programtag',
            index=models.Index(fields=['tag', 'source_method', 'is_active'], name='idx_program_tag_source'),
        ),
        migrations.AddConstraint(
            model_name='programtag',
            constraint=models.UniqueConstraint(fields=('program', 'tag', 'source_method'), name='uq_program_tag_source'),
        ),
    ]
