# Generated by Django 5.2.15 on 2026-06-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isbn13', models.CharField(blank=True, default='', help_text='문자열 ISBN입니다. 빈 문자열은 아직 ISBN 미확인 또는 미수집 상태를 뜻합니다.', max_length=13)),
                ('title', models.CharField(max_length=255)),
                ('authors_text', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=120)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=80)),
                ('addition_symbol', models.CharField(blank=True, max_length=20)),
                ('kdc_class_no', models.CharField(blank=True, max_length=40)),
                ('kdc_class_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('source_detail_url', models.URLField(blank=True, max_length=500)),
                ('provider_code', models.CharField(blank=True, max_length=40)),
                ('metadata_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='idx_book_title'), models.Index(fields=['authors_text'], name='idx_book_authors'), models.Index(fields=['is_active', 'title'], name='idx_book_active_title')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('isbn13', ''), _negated=True), fields=('isbn13',), name='uq_book_isbn13_present')],
            },
        ),
        migrations.CreateModel(
            name='PopularBookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(max_length=40)),
                ('scope_type', models.CharField(choices=[('national', '전국'), ('region', '지역')], max_length=16)),
                ('region_code', models.CharField(blank=True, max_length=40)),
                ('detail_region_code', models.CharField(blank=True, max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('query_hash', models.CharField(max_length=128)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fresh_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope_type', 'region_code', 'period_end'], name='idx_popular_snapshot_scope'), models.Index(fields=['fresh_until'], name='idx_popular_snapshot_fresh')],
                'constraints': [models.UniqueConstraint(fields=('provider_code', 'query_hash', 'period_start', 'period_end'), name='uq_popular_snapshot_query'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='popular_snapshot_period_order')],
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_method', models.CharField(choices=[('kdc_rule', 'KDC 규칙'), ('metadata_rule', '메타데이터 규칙'), ('manual', '수동')], max_length=24)),
                ('source_field', models.CharField(blank=True, max_length=80)),
                ('score', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='books.book')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_links', to='tags.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['book', 'is_active'], name='idx_book_tag_active'), models.Index(fields=['tag', 'source_method', 'is_active'], name='idx_book_tag_source')],
                'constraints': [models.UniqueConstraint(fields=('book', 'tag', 'source_method'), name='uq_book_tag_source')],
            },
        ),
        migrations.CreateModel(
            name='LibraryHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(max_length=40)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='books.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='libraries.library')),
            ],
            options={
                'indexes': [models.Index(fields=['library', 'is_active'], name='idx_holding_library_active'), models.Index(fields=['book', 'is_active'], name='idx_holding_book_active')],
                'constraints': [models.UniqueConstraint(fields=('library', 'book'), name='uq_library_book_holding')],
            },
        ),
        migrations.CreateModel(
            name='PopularBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField()),
                ('loan_count', models.PositiveIntegerField(blank=True, null=True)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='popular_items', to='books.book')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='books.popularbooksnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'rank'], name='idx_popular_item_rank')],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'rank'), name='uq_popular_item_rank'), models.UniqueConstraint(fields=('snapshot', 'book'), name='uq_popular_item_book')],
            },
        ),
    ]
