# Generated by Django 5.2.15 on 2026-06-23 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('recommendations', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferredPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('purpose', models.ForeignKey(help_text='Purpose.is_profile_selectable=True 검증은 serializer/service에서 수행합니다.', on_delete=django.db.models.deletion.PROTECT, related_name='preferred_by_users', to='recommendations.purpose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_purposes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active', 'display_order'], name='idx_user_purpose_order')],
                'constraints': [models.UniqueConstraint(fields=('user', 'purpose'), name='uq_user_preferred_purpose')],
            },
        ),
        migrations.CreateModel(
            name='UserPreferredTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tag', models.ForeignKey(help_text='Tag.is_profile_selectable=True 검증은 serializer/service에서 수행합니다.', on_delete=django.db.models.deletion.PROTECT, related_name='preferred_by_users', to='tags.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active', 'display_order'], name='idx_user_tag_order')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tag'), name='uq_user_preferred_tag')],
            },
        ),
    ]
