# Generated by Django 6.0.6 on 2026-06-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('semantic_kind', models.CharField(choices=[('objective', '객관 사실'), ('experience', '사용자 경험'), ('classification', '분류'), ('content', '콘텐츠 주제')], max_length=24)),
                ('tag_group', models.CharField(choices=[('library_type', '도서관 유형'), ('operation', '운영 조건'), ('study_reading', '공부·열람'), ('facility', '시설'), ('space_atmosphere', '공간·분위기'), ('collection', '책·자료'), ('book_subject', '책 주제'), ('program_type', '프로그램 유형'), ('program_target', '프로그램 대상'), ('kids_family', '아이·가족'), ('access_convenience', '접근·편의'), ('guidance_management', '안내·관리')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_profile_selectable', models.BooleanField(default=False)),
                ('is_review_selectable', models.BooleanField(default=False)),
                ('review_label', models.CharField(blank=True, max_length=120)),
                ('review_group', models.CharField(blank=True, choices=[('study_reading', '공부·열람'), ('space_atmosphere', '공간·분위기'), ('collection', '책·자료'), ('program', '프로그램'), ('kids_family', '아이·가족'), ('access_convenience', '접근·편의'), ('guidance_management', '안내·관리')], max_length=40)),
                ('is_filterable', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('review_display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['semantic_kind', 'tag_group', 'is_active', 'display_order'], name='idx_tag_kind_group_active'), models.Index(fields=['review_group', 'is_review_selectable', 'review_display_order'], name='idx_tag_review_options')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_review_selectable', False), models.Q(('semantic_kind', 'experience'), models.Q(('review_label', ''), _negated=True), models.Q(('review_group', ''), _negated=True), ('review_display_order__gt', 0)), _connector='OR'), name='tag_review_metadata_required')],
            },
        ),
    ]
