# Generated by Django 5.2.15 on 2026-06-23 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=80)),
                ('source_type', models.CharField(choices=[('file', '파일'), ('api', 'API'), ('crawler', '크롤러'), ('manual', '수동')], max_length=16)),
                ('target_domain', models.CharField(max_length=40)),
                ('target_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('success', '성공'), ('failed', '실패'), ('partial', '부분 성공')], db_index=True, help_text='실행 중 상태는 status=NULL, started_at 존재, finished_at=NULL로 해석합니다.', max_length=16, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='API 키, Authorization, serviceKey, authKey 등 민감 정보를 제거한 값만 저장합니다.')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='외부 원문 응답 전체가 아니라 민감 정보가 제거된 실행 요약만 저장합니다.')),
                ('error_message', models.TextField(blank=True)),
                ('report_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'indexes': [models.Index(fields=['source_name', '-started_at'], name='idx_sync_source_started'), models.Index(fields=['status', '-started_at'], name='idx_sync_status_started'), models.Index(fields=['target_year', 'target_month'], name='idx_sync_target_period'), models.Index(fields=['target_domain', '-started_at'], name='idx_sync_domain_started')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_month__isnull', True), models.Q(('target_month__gte', 1), ('target_month__lte', 12)), _connector='OR'), name='source_sync_month_range')],
            },
        ),
    ]
